config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  mount UrBetterHouse::API => '/api'
  devise_for :admins
  devise_for :users
  resources :residentials
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :residential
end

app/models/residential.rb
class Residential < ApplicationRecord
    validates :title, presence: true
    validates :thumb_pic, format: { with: /(https?:\/\/.*\.(?:png|jpg))/i, message: "only allow url with png/jpg extension" }
    validates :price_per_month, numericality:{ in: 30000..100000 }
    validates :address, presence: true # TODO address format
    validates :total_room, presence: true
    validates :livingroom, presence: true

    has_many :favorites

    # def self.filter_by(filters = nil)
    #     return all if filters.nil?
    #     if filters.size > 0
    #         return where(**filters)
    #     else
    #         all
    #     end
    # end

    def liked(options)
        self.favorites.where(user_id: options[:user_id]).size > 0
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :token_authenticatable
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/residentials_controller.rb
class ResidentialsController < ApplicationController
  before_action :set_residential, only: %i[ show edit update destroy ]

  # GET /residentials or /residentials.json
  def index
    @residentials = Residential.all
  end

  # GET /residentials/1 or /residentials/1.json
  def show
  end

  # GET /residentials/new
  def new
    @residential = Residential.new
  end

  # GET /residentials/1/edit
  def edit
  end

  # POST /residentials or /residentials.json
  def create
    @residential = Residential.new(residential_params)

    respond_to do |format|
      if @residential.save
        format.html { redirect_to residential_url(@residential), notice: "Residential was successfully created." }
        format.json { render :show, status: :created, location: @residential }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @residential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residentials/1 or /residentials/1.json
  def update
    respond_to do |format|
      if @residential.update(residential_params)
        format.html { redirect_to residential_url(@residential), notice: "Residential was successfully updated." }
        format.json { render :show, status: :ok, location: @residential }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @residential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residentials/1 or /residentials/1.json
  def destroy
    @residential.destroy

    respond_to do |format|
      format.html { redirect_to residentials_url, notice: "Residential was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residential
      @residential = Residential.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def residential_params
      params.require(:residential).permit(:thumb_pic, :title, :price_per_month, :address, :total_room, :livingroom, :has_mrt, :mrt_line)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/residentials_helper.rb
module ResidentialsHelper
end

app/views/home/index.html.erb
<%= react_component "UrBetterHouseApp" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrBetterHouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />

  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/residentials/_form.html.erb
<%= form_with(model: residential, local: true) do |form| %>
  <% if residential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(residential.errors.count, "error") %> prohibited this residential from being saved:</h2>

      <ul>
        <% residential.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :thumb_pic %>
    <%= form.text_field :thumb_pic %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price_per_month %>
    <%= form.number_field :price_per_month %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :total_room %>
    <%= form.number_field :total_room %>
  </div>

  <div class="field">
    <%= form.label :livingroom %>
    <%= form.number_field :livingroom %>
  </div>

  <div class="field">
    <%= form.label :has_mrt %>
    <%= form.check_box :has_mrt %>
  </div>

  <div class="field">
    <%= form.label :mrt_line %>
    <%= form.text_field :mrt_line %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/residentials/edit.html.erb
<h1>Editing Residential</h1>

<%= render 'form', residential: @residential %>

<%= link_to 'Show', @residential %> |
<%= link_to 'Back', residentials_path %>

app/views/residentials/index.html.erb
<h1>Residentials</h1>

<table>
  <thead>
    <tr>
      <th>Thumb pic</th>
      <th>Title</th>
      <th>Price per month</th>
      <th>Address</th>
      <th>Total room</th>
      <th>Livingroom</th>
      <th>Has mrt</th>
      <th>Mrt line</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residentials.each do |residential| %>
      <tr>
        <td><%= residential.thumb_pic %></td>
        <td><%= residential.title %></td>
        <td><%= residential.price_per_month %></td>
        <td><%= residential.address %></td>
        <td><%= residential.total_room %></td>
        <td><%= residential.livingroom %></td>
        <td><%= residential.has_mrt %></td>
        <td><%= residential.mrt_line %></td>
        <td><%= link_to 'Show', residential %></td>
        <td><%= link_to 'Edit', edit_residential_path(residential) %></td>
        <td><%= link_to 'Destroy', residential, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Residential', new_residential_path %>

app/views/residentials/new.html.erb
<h1>New Residential</h1>

<%= render 'form', residential: @residential %>

<%= link_to 'Back', residentials_path %>

app/views/residentials/show.html.erb
<p>
  <strong>Thumb pic:</strong>
  <%= @residential.thumb_pic %>
</p>

<p>
  <strong>Title:</strong>
  <%= @residential.title %>
</p>

<p>
  <strong>Price per month:</strong>
  <%= @residential.price_per_month %>
</p>

<p>
  <strong>Address:</strong>
  <%= @residential.address %>
</p>

<p>
  <strong>Total room:</strong>
  <%= @residential.total_room %>
</p>

<p>
  <strong>Livingroom:</strong>
  <%= @residential.livingroom %>
</p>

<p>
  <strong>Has mrt:</strong>
  <%= @residential.has_mrt %>
</p>

<p>
  <strong>Mrt line:</strong>
  <%= @residential.mrt_line %>
</p>

<%= link_to 'Edit', edit_residential_path(@residential) %> |
<%= link_to 'Back', residentials_path %>